// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TransactionJournal.Data;

#nullable disable

namespace TransactionJournal.Data.Migrations
{
	[DbContext(typeof(JournalDbContext))]
	[Migration("20260920094901_InitialRawStorage")]
	partial class InitialRawStorage
	{
		/// <inheritdoc />
		protected override void BuildTargetModel(ModelBuilder modelBuilder)
		{
#pragma warning disable 612, 618
			modelBuilder.HasAnnotation("ProductVersion", "9.0.12");

			modelBuilder.Entity("TransactionJournal.Data.RawDelivery", b =>
				{
					b.Property<long>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("INTEGER");

					b.Property<string>("Category")
						.IsRequired()
						.HasColumnType("TEXT");

					b.Property<long>("DeliveryTimeMs")
						.HasColumnType("INTEGER");

					b.Property<DateTimeOffset>("FetchedAt")
						.HasColumnType("TEXT");

					b.Property<string>("PayloadJson")
						.IsRequired()
						.HasColumnType("TEXT");

					b.Property<string>("Symbol")
						.IsRequired()
						.HasColumnType("TEXT");

					b.HasKey("Id");

					b.HasIndex("Symbol", "DeliveryTimeMs")
						.IsUnique();

					b.ToTable("RawDeliveries");
				});

			modelBuilder.Entity("TransactionJournal.Data.RawExecution", b =>
				{
					b.Property<long>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("INTEGER");

					b.Property<string>("Category")
						.IsRequired()
						.HasColumnType("TEXT");

					b.Property<string>("ExecId")
						.IsRequired()
						.HasColumnType("TEXT");

					b.Property<long>("ExecTimeMs")
						.HasColumnType("INTEGER");

					b.Property<DateTimeOffset>("FetchedAt")
						.HasColumnType("TEXT");

					b.Property<string>("PayloadJson")
						.IsRequired()
						.HasColumnType("TEXT");

					b.Property<string>("Symbol")
						.IsRequired()
						.HasColumnType("TEXT");

					b.HasKey("Id");

					b.HasIndex("ExecId")
						.IsUnique();

					b.ToTable("RawExecutions");
				});

			modelBuilder.Entity("TransactionJournal.Data.RawInstrument", b =>
				{
					b.Property<long>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("INTEGER");

					b.Property<string>("Category")
						.IsRequired()
						.HasColumnType("TEXT");

					b.Property<DateTimeOffset>("FetchedAt")
						.HasColumnType("TEXT");

					b.Property<string>("PayloadJson")
						.IsRequired()
						.HasColumnType("TEXT");

					b.Property<string>("Symbol")
						.IsRequired()
						.HasColumnType("TEXT");

					b.HasKey("Id");

					b.HasIndex("Symbol")
						.IsUnique();

					b.ToTable("RawInstruments");
				});

			modelBuilder.Entity("TransactionJournal.Data.SyncRun", b =>
				{
					b.Property<long>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("INTEGER");

					b.Property<string>("Error")
						.HasColumnType("TEXT");

					b.Property<DateTimeOffset?>("FinishedAt")
						.HasColumnType("TEXT");

					b.Property<string>("Mode")
						.IsRequired()
						.HasColumnType("TEXT");

					b.Property<int>("NewDeliveries")
						.HasColumnType("INTEGER");

					b.Property<int>("NewExecutions")
						.HasColumnType("INTEGER");

					b.Property<int>("NewInstruments")
						.HasColumnType("INTEGER");

					b.Property<DateTimeOffset>("StartedAt")
						.HasColumnType("TEXT");

					b.Property<string>("Status")
						.IsRequired()
						.HasColumnType("TEXT");

					b.HasKey("Id");

					b.ToTable("SyncRuns");
				});

			modelBuilder.Entity("TransactionJournal.Data.SyncState", b =>
				{
					b.Property<long>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("INTEGER");

					b.Property<long?>("BackfillBoundaryMs")
						.HasColumnType("INTEGER");

					b.Property<string>("Category")
						.IsRequired()
						.HasColumnType("TEXT");

					b.Property<long?>("DeliveryWatermarkMs")
						.HasColumnType("INTEGER");

					b.Property<long?>("ExecWatermarkMs")
						.HasColumnType("INTEGER");

					b.Property<DateTimeOffset?>("LastSuccessAt")
						.HasColumnType("TEXT");

					b.HasKey("Id");

					b.HasIndex("Category")
						.IsUnique();

					b.ToTable("SyncStates");
				});
#pragma warning restore 612, 618
		}
	}
}
