namespace TransactionJournal.Data;

/// <summary>
/// Ручной статус конструкции. «Открыта» — значение по умолчанию для новых
/// конструкций; «архив» скрывает конструкцию из активных списков, сохраняя
/// её и историю в аналитике. Автоматической смены статуса нет.
// Traceability: change:add-core-domain/design#d4
/// </summary>
public enum ConstructionStatus
{
	/// <summary>Конструкция активна и видна в активных списках.</summary>
	Open,

	/// <summary>Конструкция закрыта пользователем, но не скрыта из списков.</summary>
	Closed,

	/// <summary>Конструкция скрыта из активных списков и остаётся только в аналитике.</summary>
	Archived,
}

/// <summary>
/// Единица измерения плановой границы результата конструкции: пользователь
/// вводит риск и профит значением ровно в одной единице, и введённая единица
/// хранится первоисточником, а незаполненная вычисляется при чтении.
/// </summary>
// Единица ввода — часть параметра «риск/профит»: она определяет, какая
// величина первична, а какая вычисляется от капитала при чтении.
// Traceability: openspec:domain/constructions#requirement-risk-profit-params
public enum TargetUnit
{
	/// <summary>Значение введено в процентах от выделенного капитала.</summary>
	Percent,

	/// <summary>Значение введено в USDT.</summary>
	Usdt,
}

/// <summary>
/// Именованное логическое объединение сделок вокруг одной торговой цели:
/// выделенный капитал, ручной статус, плановые границы результата и
/// комментарий. Единственный мутируемый агрегат домена — позиции и результаты
/// выводятся из сделок при чтении.
// Traceability: openspec:domain/constructions#requirement-construction-management
/// Traceability: change:add-core-domain/design#d1
/// </summary>
public sealed class Construction
{
	/// <summary>Суррогатный ключ строки хранилища.</summary>
	public long Id { get; set; }

	/// <summary>Имя конструкции, свободно переименовывается без влияния на прочие данные.</summary>
	public required string Name { get; set; }

	/// <summary>
	/// Признак вручную зафиксированного имени: выставляется ручным переименованием
	/// и отключает автогенерацию имени сборкой для этой конструкции.
	/// </summary>
	// Флаг — единственная точка отключения автогенерации имени: пока он не
	// выставлен, сборка пересчитывает имя из текущего состава живых опционных
	// ног; полный пересбор стирает конструкцию целиком, и флаг уходит вместе с ней.
	// Traceability: change:refine-construction-assembly/design#d6
	// Traceability: change:refine-construction-assembly/specs/domain/constructions/spec#scenario-rename-locks-autogenerated-name
	public bool NameIsManual { get; set; }

	/// <summary>Ручной статус конструкции; по умолчанию новые конструкции открываются со статусом «открыта».</summary>
	public ConstructionStatus Status { get; set; }

	/// <summary>
	/// Выделенный капитал в USDT — текущее значение без истории изменений;
	/// база для расчёта процентов результата конструкции. Значение может
	/// отсутствовать: конструкция допускается без выделенного бюджета, и тогда
	/// процентные величины результата не вычисляются.
	/// </summary>
	// Незаданный капитал не образует базы процентов: процентные величины
	// отсутствуют, абсолютные результаты не меняются.
	// Traceability: openspec:domain/constructions#requirement-allocated-capital
	public decimal? AllocatedCapitalUsdt { get; set; }

	/// <summary>
	/// Значение риска — допустимого убытка конструкции; вводится положительным
	/// числом в единице <see cref="RiskUnit"/> и хранится текущим без истории
	/// изменений. Пара «значение + единица» либо задана целиком, либо оба поля
	/// пусты — параметр риска отсутствует.
	/// </summary>
	// Введённая единица — первоисточник параметра: незаполненная единица
	// вычисляется от капитала при чтении и в базе не хранится.
	// Traceability: openspec:domain/constructions#requirement-risk-profit-params
	public decimal? RiskValue { get; set; }

	/// <summary>Единица ввода риска — проценты или USDT; null означает, что параметр риска не задан.</summary>
	public TargetUnit? RiskUnit { get; set; }

	/// <summary>
	/// Значение профита — целевой прибыли конструкции; вводится положительным
	/// числом в единице <see cref="ProfitUnit"/> и хранится текущим без истории
	/// изменений. Пара «значение + единица» либо задана целиком, либо оба поля
	/// пусты — параметр профита отсутствует.
	/// </summary>
	// Введённая единица — первоисточник параметра: незаполненная единица
	// вычисляется от капитала при чтении и в базе не хранится.
	// Traceability: openspec:domain/constructions#requirement-risk-profit-params
	public decimal? ProfitValue { get; set; }

	/// <summary>Единица ввода профита — проценты или USDT; null означает, что параметр профита не задан.</summary>
	public TargetUnit? ProfitUnit { get; set; }

	/// <summary>Свободный комментарий пользователя к конструкции.</summary>
	public string? Comment { get; set; }
}
